### PR TITLE
 Visitation Schema Update

### PR DESCRIPTION
**Pull request by safil-badarudeen**
- added date
- end hour , start hour
- Home id with reference to homes schema model
- modified start hour , end hour type to date from Sting  to specify time exclusively

### CODE REVIEW

**Comment by DamyanBG** [comment]
Target branch have to be development

**Comment by safil-badarudeen** [comment]
should i need to create a new pull request to set target branch

**Comment by DamyanBG** [comment]
Yes

**Comment by safil-badarudeen** [comment]
can i know how can i set up  a target branch, any blog or something i could nt find any particular article ,  IF I  want to set target branch do i need to push without forking , sorry if you r busy, but if i coluld understand it i could make more pull request and help you

**Comment by safil-badarudeen** [comment]
Thanks , image you provided where really helpful

**Pull request closed without merging**
