### PR TITLE
Change import syntax from require to import

### PR DESCRIPTION
**Pull request by rhinoxD**
Closes https://github.com/DamyanBG/real-estate-nodejs-be/issues/86

### CODE REVIEW

**Comment by DamyanBG** [comment]
Please, target development branch.

**Review by DamyanBG — CHANGES_REQUESTED** [review]
Still I can see there are conflicts

**Comment by DamyanBG** [comment]
I will stop adding new stuffs until you are ready with the conflicts.

**Comment by rhinoxD** [comment]
So I have to make changes to these files again right?
image

**Comment by rhinoxD** [comment]
By mistake I created a new branch and made a pr, so should I close the new pr and make changes here or let it be?

**Comment by DamyanBG** [comment]
It is your choice

**Review by DamyanBG — APPROVED** [review]

**Pull request merged**
